<?php

/**
 * auth.php — Authentication routes (provided by Laravel Breeze)
 *
 * Two route groups:
 *
 * 1. 'guest' middleware group — only accessible when NOT logged in.
 *    Redirects authenticated users away (prevents logged-in users from seeing /login).
 *    Covers: register, login, forgot password, reset password.
 *
 * 2. 'auth' middleware group — only accessible when logged in.
 *    Covers: email verification, confirm password, change password, logout.
 *
 * All POST routes are automatically protected by Laravel's CSRF middleware,
 * which validates the _token field generated by @csrf in Blade forms.
 */

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\ConfirmablePasswordController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\EmailVerificationPromptController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Auth\VerifyEmailController;
use Illuminate\Support\Facades\Route;

// ---------------------------------------------------------------
// Guest-only routes (unauthenticated users only)
// ---------------------------------------------------------------
Route::middleware('guest')->group(function () {

    // Registration form + submission
    Route::get('register',  [RegisteredUserController::class, 'create'])->name('register');
    Route::post('register', [RegisteredUserController::class, 'store']);

    // Login form + submission (password verified via password_verify() internally)
    Route::get('login',  [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);

    // Forgot password: shows the email form, then sends the reset link
    Route::get('forgot-password',  [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');

    // Password reset: tokenized URL from email, then processes the new password
    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('reset-password',        [NewPasswordController::class, 'store'])->name('password.store');
});

// ---------------------------------------------------------------
// Authenticated routes (logged-in users only)
// ---------------------------------------------------------------
Route::middleware('auth')->group(function () {

    // Email verification notice and handler
    // 'signed' middleware ensures the link hasn't been tampered with
    Route::get('verify-email', EmailVerificationPromptController::class)->name('verification.notice');
    Route::get('verify-email/{id}/{hash}', VerifyEmailController::class)
        ->middleware(['signed', 'throttle:6,1'])
        ->name('verification.verify');

    // Re-send verification email (rate-limited to 6 per minute)
    Route::post('email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
        ->middleware('throttle:6,1')
        ->name('verification.send');

    // Confirm password before accessing sensitive areas
    Route::get('confirm-password',  [ConfirmablePasswordController::class, 'show'])->name('password.confirm');
    Route::post('confirm-password', [ConfirmablePasswordController::class, 'store']);

    // Change password (requires current password verification)
    Route::put('password', [PasswordController::class, 'update'])->name('password.update');

    // Logout: destroys the session and invalidates the CSRF token
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});
